#!/bin/sh

passfail {
    if "$1" -eq 0; then
	echo PASS
    else
	echo FAIL
    fi
}

rkt --insecure-options=image run \
    --mds-register \
    --volume=database,kind=host,source=/tmp \
    https://github.com/appc/spec/releases/download/v0.7.4/ace-validator-main.aci \
    https://github.com/appc/spec/releases/download/v0.7.4/ace-validator-sidekick.aci

echo "$(passfail $?): appc ACE validator"

exit 0
